language: node_js
node_js:
- node
- '9'
cache: yarn
script: echo 0
deploy:
  provider: npm
  email: igor@kamyshev.me
  skip_cleanup: true
  api_key:
    secure: X0LSM9NJL9J6J0ojxLoTqF4drI48mpaVG36AUforRYjbhvyP9g+Rsw3zxY9kifi3wQ07PXnRPa3225KpdGaDGh9tAAb+GegoQBWkgYoY86GLAmjX0vVTMyygKVJt0m29/ing1aAq936Q1LVUV9fIsQcXHOuIOpVIVakS8TtF4STIXHw1mW35tjd2nZtfvsC2ZjlkhiUbTgWKC5vcApMJ7ZjLFIHP7AqatfoMfgd/uVZw2OB8IcrZGPYBHNc4rWqJBazWlz9Ihm9/n7KjM53oN5RFm6tjhYPJkMH9sVWvPji1MjwRh0s2aQ2yLd6y80e/HqPMaf5uUNp4mwyS69lT3hN6u0njFtmG5fTbLRiaZpC0GnjT7rZ8yvUYoBQ7G6obhT+8OOEHZp7qaUjLNqJI7fm0ne16fQBjDqyZhyLva0VRsf/K98NSgJmegytKb0hNiMaUr3IRmvdNUxCMKGpDKooNpwRlwXd9ibPuszFNj3CAmrJKAe3aIFwyfuBQs5TyXFTucxZWN5Tb3QRToe31nwCFaPMs1fHmLJgopjhv8HVCqYwOBBzrGrW5WI3MBrhs3q0Pc2DavLTY7492qf981UGdB5PjIHgv5tfm3bMNIGRUD8HiceYC28qW/TjLxpLToWzIUy4NC6vGNj0rgi8TSxBPkIyGcGmIAzHAbvWo5ng=
  on:
    tags: true
    repo: igorkamyshev/react-timeline-scribble
